name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: ./github_actions_key
          script: |
            sudo sh -c '
              cd /opt/stacks/agnel-arena
              git fetch --all
              git reset --hard origin/main
              ./deploy.sh
            '
